apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: guardian-tenant-admin
rules:
- apiGroups: [""]
  resources: ["resourcequotas","limitranges"]
  verbs: ["get","list","watch","create","update","patch","delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get","list","watch","create","update","patch","delete"]

