# This rule is not used by the project namespace-guardian itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to guardian.guardian.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: namespace-guardian
    app.kubernetes.io/managed-by: kustomize
  name: namespacerequest-viewer-role
rules:
- apiGroups:
  - guardian.guardian.io
  resources:
  - namespacerequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - guardian.guardian.io
  resources:
  - namespacerequests/status
  verbs:
  - get
